# This file contains default values, and does not need to be edited. All
# important settings can be changed from the admin interface.

defaults: &defaults
  site_title: Mastodon
  site_short_description: ''
  site_description: ''
  site_extended_description: ''
  site_terms: ''
  site_contact_username: ''
  site_contact_email: ''
  registrations_mode: 'open'
  profile_directory: true
  closed_registrations_message: ''
  open_deletion: true
  min_invite_role: 'admin'
  timeline_preview: true
  show_staff_badge: true
  show_moderator_badge: true
  default_sensitive: false
  hide_network: false
  unfollow_modal: false
  unsubscribe_modal: false
  boost_modal: false
  delete_modal: true
  auto_play_gif: false
  display_media: 'default'
  expand_spoilers: false
  preview_sensitive_media: false
  reduce_motion: false
  disable_swiping: false
  show_application: true
  system_font_ui: false
  noindex: false
  theme: 'default'
  theme_instance_ticker: 'none'
  theme_public: true
  aggregate_reblogs: true
  advanced_layout: false
  use_blurhash: true
  use_pending_items: false
  trends: true
  trendable_by_default: false
  crop_images: true
  confirm_domain_block: true
  show_follow_button_on_timeline: false
  show_subscribe_button_on_timeline: false
  show_followed_by: false
  follow_button_to_list_adder: false
  show_navigation_panel: true
  show_bookmark_button: true
  show_quote_button: true
  show_target: false
  place_tab_bar_at_bottom: false
  show_tab_bar_label: false
  enable_federated_timeline: true
  enable_limited_timeline: false
  enable_personal_timeline: false
  enable_personal_account: false
  enable_local_timeline: true
  enable_reaction: true
  compact_reaction: false
  show_reply_tree_button: true
  hide_statuses_count: false
  hide_following_count: false
  hide_followers_count: false
  disable_joke_appearance: false
  new_features_policy: 'default'
  enable_status_reference: true
  content_font_size: 15
  info_font_size: 15
  content_emoji_reaction_size: 16
  emoji_scale: 1,
  picker_emoji_size: 22,
  notification_emails:
    follow: false
    reblog: false
    favourite: false
    emoji_reaction: false
    status_reference: false
    mention: false
    follow_request: true
    digest: true
    report: true
    pending_account: true
    trending_tag: true
  interactions:
    must_be_dm_to_send_email: false
    must_be_follower: false
    must_be_following: false
    must_be_following_dm: false
    must_be_following_reference: true
  reserved_usernames:
    - admin
    - support
    - help
    - root
    - webmaster
    - administrator
    - mod
    - moderator
  disallowed_hashtags: # space separated string or list of hashtags without the hash
  bootstrap_timeline_accounts: ''
  activity_api_enabled: true
  peers_api_enabled: true
  show_known_fediverse_at_about_page: true
  show_domain_blocks: 'disabled'
  show_domain_blocks_rationale: 'disabled'
  require_invite_text: false
  match_visibility_of_references: true
  post_reference_modal: false
  add_reference_modal: true
  unselect_reference_modal: false
  delete_scheduled_status_modal: true
  hexagon_avatar: false
  enable_empty_column: false
  hide_bot_on_public_timeline: false
  confirm_follow_from_bot: true
  default_search_searchability: 'public'
  show_reload_button: true
  default_column_width: 'x100'
  default_expires_in: ''
  default_expires_action: 'mark'
  disable_post: false
  disable_reactions: false
  disable_follow: false
  disable_unfollow: false
  disable_block: false
  disable_domain_block: false
  disable_clear_all_notifications: false
  disable_account_delete: false
  prohibited_visibilities: []
  prohibited_words: ''
  disable_relative_time: false
  hide_direct_from_timeline: false
  hide_personal_from_timeline: false
  hide_privacy_meta: false

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
